---
name: Template-Multilingual
version: 0.01
author:
  - Eric Cholet <cholet@logilune.com>
abstract: Multilingal templates for Template Toolkit
license: perl
requires:
  Template: 2
  Test::More: 0
provides:
  Template::Multilingual:
    file: lib/Template/Multilingual.pm
    version: 0.01
  Template::Multilingual::Parser:
    file: lib/Template/Multilingual/Parser.pm
    version: 0.01
generated_by: Module::Build version 0.2609
