---
name: Template-Multilingual
version: 0.08
author:
  - 'Eric Cholet <cholet@logilune.com>'
abstract: Multilingual templates for Template Toolkit
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template: 2
  Test::More: 0
provides:
  Template::Multilingual:
    file: lib/Template/Multilingual.pm
    version: 0.08
  Template::Multilingual::Parser:
    file: lib/Template/Multilingual/Parser.pm
    version: 0.08
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
